version: '3.7'
services:
  freeipa:
#    image: freeipa/freeipa-server:centos-8-stream
    build: 
      context: freeipa-container/
      dockerfile: Dockerfile.centos-8-stream
    restart: unless-stopped
    container_name: freeipa
    hostname: freeipa
    domainname: eth.su
    cap_add:
      - SYS_TIME
#    privileged: true
    environment:
      IPA_SERVER_HOSTNAME: freeipa.eth.su
      IPA_SERVER_IP: 10.10.0.12 
      TIME_ZONE: "Europe/Moscow"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ipa-data:/data:rw
      - ipa-logs:/var/log:rw
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
    command:
      - --unattended
      - --domain=eth.su
      - --realm=ETH.SU
      - --http-pin=YOURPASSWORD
      - --dirsrv-pin=YOURPASSWORD
      - --ds-password=YOURPASSWORD
      - --admin-password=YOURPASSWORD
      - --setup-dns
      - --no-forwarders
      - --no-host-dns
      - --auto-reverse
      - --no-dnssec-validation
      - --allow-zone-overlap
    networks:
      - freeipa
    ports:
      - "80:80"
      - "443:443"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "53:53"
      - "88:88/udp"
      - "464:464/udp"
      - "123:123/udp"
      - "53:53/udp"
      - "7389:7389"
      - "9443:9443"
      - "9444:9444"
      - "9445:9445"
    dns:
      - 127.0.0.1
    security_opt:
      - "seccomp:unconfined"
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'
volumes:
  ipa-data:
  ipa-logs:
networks:
  freeipa:
    name: freeipa-network


